args <- commandArgs(TRUE)
pkg <- args[[1]]
library(ggplot2)
env <- new.env(parent = globalenv())
for (file in list.files(file.path(pkg, "R"), full.names = TRUE)) sys.source(file, envir = env)
exports <- ls(env)
# Resolve unqualified function calls to explicit namespace imports.
providers <- c("dplyr", "tidyr", "grid", "ggplot2", "rlang", "purrr", "flextable", "here", "grDevices", "stats", "utils", "coin")
known <- lapply(providers, getNamespaceExports)
names(known) <- providers
calls <- unique(unlist(lapply(mget(exports, env), function(x) if(is.function(x)) codetools::findGlobals(x, merge = TRUE) else character())))
# theme_layout is a top-level ggplot theme object.
calls <- union(calls, c("theme", "element_rect", "element_blank", "element_line", "element_text"))
calls <- setdiff(calls, c(exports, ls(baseenv(), all.names = TRUE)))
imports <- 'importFrom(pals,"kelly")'
for (call in sort(calls)) {
  hit <- providers[vapply(known, function(x) call %in% x, logical(1))]
  if (length(hit)) imports <- c(imports, sprintf('importFrom(%s,"%s")', hit[1], call))
}
writeLines(c('# Generated by dev/build_package.py; edit canonical scripts in R/.', sprintf('export("%s")', exports), imports), file.path(pkg, "NAMESPACE"))
dir.create(file.path(pkg, "man"), showWarnings = FALSE)
for (name in exports) {
  writeLines(c(paste0("\\name{",name,"}"),paste0("\\alias{",name,"}"),paste0("\\title{",gsub("_", " ", name),"}"),
    "\\description{Versioned laboratory analysis helper, preserved from the central R functions collection.}",
    "\\details{Use the function's arguments to supply data and plot settings. Plot size defaults use the ktools.fontsize, ktools.pointsize and ktools.linewidth R options (7, 1 and 1). The legacy_file accessor returns a script from this installed package version, for compatibility with existing source calls.}",
    "\\seealso{\\code{args}, \\code{packageVersion}}"), file.path(pkg,"man",paste0(name,".Rd")))
}

writeLines('utils::globalVariables(c(".y_range", "bracket_y_range", "comp_rank", "data_input", "Dodge_col", "dodge_numeric", "Facet_col", "Group_col", "group1", "group2", "ID_Col", "p", "Statistic", "test_result", "Value", "Variable", "x_dodge", "xmax", "xmin", "y_bracket", "y_max", "y.position", "yData_col", "yMax", "yMax_bigger"))', file.path(pkg, "R/zzz-globals.R"))
