experiment_name: "2025-02-26_Project Relax_Hematoma"

theme: 
  fontfamily: "Arial"
  FontSize: 10
  PointSize: 1
  LineWidth: 1

scaling_factors:
  title: 1.2
  axistext: 1
  legendtext: 1

Color.Gels:
  Slow: "#D6604D"
  MVG: "#D6604D"
  Fast: "#4393C3"
  VLVG: "#4393C3"
  Hematoma: "#762A83"

path_Rfunctions: "C:/Users/knechtrs/OneDrive - Charité - Universitätsmedizin Berlin/Data_analysis/R_functions"

metaData:
  - PatientLetter
  - Patient
  - PatientNumber
  
RemoveSample: 
  - "Z Patient 006" # too noisy
#  - "C Patient 001"
  - "G Patient 012" # dpi not clearly noted
  - "F Patient 009" # too old: dpi 12
#  - "J Patient 13A"

FilterParams:
  order: 2
  cutoff: 0.1

Emod_low: 0.08
Emod_high: 0.12

tMax: 3000 # set to 3000 for better fits of tau2

maxwell_fit_script: "bose analysis/Maxwell_fit function_v1.R"
