---
title: "Analysis Template"
author: "Raphael S. Knecht"
date: today
format: html
editor: visual
---

```{r setup}

# # restore r-environment with loaded pacakges. At project-initialization this has already been done.
# renv::restore()

# ---- Load libraries ----
library(here)
library(tidyverse)      # includes dplyr, ggplot2, readr, etc.
library(ggtext)
library(ggrepel)
library(ggpubr)
library(rstatix)
library(yaml)
library(cowplot)
library(sessioninfo)
library(ggforce)

# ---- renv management ----
# This project already has renv initialized via setup script.
# If you install new packages, run:
#   install.packages("pkgname")
#   renv::snapshot()
```

## Load Configurations

```{r}
# Define path to R_functions
path_Data_analysis <- stringr::str_extract(here::here(), ".*Data_analysis")
path_Rfunctions <- file.path(path_Data_analysis, "R_functions")
```

```{r}
source(here(path_Rfunctions, "R/config/load_yaml.R"))
```

## Load Core Functions

```{r}
source(here(path_Rfunctions, "R/core/create_summary_table.R"))
source(here(path_Rfunctions, "R/core/format_pvalue.R"))
```

## Load Plotting Tools

```{r}
source(here(path_Rfunctions, "R/plotting/add_stat_test_dodge.R"))
source(here(path_Rfunctions, "R/plotting/plot_paired_points.R"))
source(here(path_Rfunctions, "R/plotting/plot_summary_points.R"))
```

## Load Custom Themes

```{r}
source(here(path_Rfunctions, "R/theme/theme_fontsize.R"))
source(here(path_Rfunctions, "R/theme/theme_layout.R"))
```

## Output Directories

```{r}
output_dir <- here("outputs", "figures_final", "version_1")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
```

## Load Configurations and Theme Parameters

```{r load-config}
# Load default param.yaml
params <- load_yaml(default_file = here("config", "params.yaml"))

# # Optionally override theme settings
# # PowerPoint
# params <- load_yaml(override_file = here("config", "theme_settings_ppt.yaml"))
# # Poster
# params <- load_yaml(override_file = here("config", "theme_settings_poster.yaml"))
# # Publication
# params <- load_yaml(override_file = here("config", "theme_settings_publication.yaml"))

# Set theme parameters
FontSize <- params$theme$FontSize
PointSize <- params$theme$PointSize
LineWidth <- params$theme$LineWidth
Color.Gels <- params$Color.Gels
```

# Import data from data/raw folder

```{r}

# get list with data files
list.csv <- list.files(path = here("data/raw"), pattern = "\\.csv|\\.CSV", recursive=FALSE, full.names=TRUE) 

# Create clean names
Names_list.csv <- list.csv %>%
  basename() %>%                # remove full folder path
  str_remove("\\.csv$|\\.CSV$")  # remove .csv extension only

# create list with files
list_data <- list.csv %>% 
  map(read_delim, delim=";") %>% # skip first row with meta.data
  setNames(Names_list.csv) # add filename to the list items

# check out problems
map(list_data, ~problems(.x))

# bind list to dataframe
df_data_raw <- list_data %>% 
  bind_rows(.id="exp") 
```
