---
title: "Analysis Template"
author: "Raphael S. Knecht"
date: today
format: html
editor: visual
---

```{r setup}

# # restore r-environment with loaded pacakges. At project-initialization this has already been done.
# renv::restore()

# ---- Load libraries ----
library(here)
library(tidyverse)      # includes dplyr, ggplot2, readr, etc.
library(ggtext)
library(ggrepel)
library(ggpubr)
library(rstatix)
library(yaml)
library(cowplot)
library(sessioninfo)
library(ggforce)
library(minpack.lm) # needed for curve fitting!

# ---- renv management ----
# This project already has renv initialized via setup script.
# If you install new packages, run:
#   install.packages("pkgname")
#   renv::snapshot()
```

## Load Configurations

```{r}
# Define path to R_functions
path_Data_analysis <- stringr::str_extract(here::here(), ".*Data_analysis")
path_Rfunctions <- file.path(path_Data_analysis, "R_functions")
```

```{r}
source(here(path_Rfunctions, "R/config/load_yaml.R"))
```

## Load Core Functions

```{r}
source(here(path_Rfunctions, "R/core/create_summary_table.R"))
source(here(path_Rfunctions, "R/core/format_pvalue.R"))
```

## Load Plotting Tools

```{r}
source(here(path_Rfunctions, "R/plotting/add_stat_test_dodge.R"))
source(here(path_Rfunctions, "R/plotting/plot_paired_points.R"))
source(here(path_Rfunctions, "R/plotting/plot_summary_points.R"))
```

## Load Custom Themes

```{r}
source(here(path_Rfunctions, "R/theme/theme_fontsize.R"))
source(here(path_Rfunctions, "R/theme/theme_layout.R"))
```

## Load bose analysis

```{r}
# needed in Import_process_data.R
source(here(path_Rfunctions, "R/bose_analysis", "read_units.R"))
source(here(path_Rfunctions, "R/bose_analysis", "clean_unit_names.R"))

# overview plot
source(here(path_Rfunctions, "R/bose_analysis", "plot_load_time.R"))

```

## Output Directories

```{r}
output_dir <- here("outputs", "figures_final", "version_1")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
```

## Load Configurations and Theme Parameters

```{r load-config}
# Load default param.yaml
params <- load_yaml(default_file = here("config", "params.yaml"))

# # Optionally override theme settings
# # PowerPoint
# params <- load_param(override_file = here("config", "theme_settings_ppt.yaml"))
# # Poster
# params <- load_param(override_file = here("config", "theme_settings_poster.yaml"))
# # Publication
# params <- load_param(override_file = here("config", "theme_settings_publication.yaml"))

# Set theme parameters
FontSize <- params$theme$FontSize
PointSize <- params$theme$PointSize
LineWidth <- params$theme$LineWidth
Color.Gels <- params$Color.Gels
```

# Import data from data/raw folder

```{r}

# get list with data files
list.csv <- list.files(path = here("data/raw"), pattern = "\\.csv|\\.CSV", recursive=FALSE, full.names=TRUE) 

# Create clean names
Names_list.csv <- list.csv %>%
  basename() %>%                # remove full folder path
  str_remove("\\.csv$|\\.CSV$")  # remove .csv extension only

# create list with files
list_data <- list.csv %>% 
  map(read_delim, delim=",", skip = 17, show_col_types= FALSE) %>% 
  setNames(Names_list.csv) # add filename to the list items

# bind list to dataframe
df_data_raw <- list_data %>% 
  map(~ slice(.x, -1)) %>% # delete first row with units
  bind_rows(.id = "exp") %>% 
  select(c("exp", "Elapsed Time ", "Disp  ", "Load 3")) %>% 
  rename(
    "time" = "Elapsed Time ",
    "disp" = "Disp  ",
    "load" = "Load 3"
  ) %>% 
  mutate(across(c(time, disp, load), as.double))
 
```

```{r}
#---- create metadata columns ----#
metaData <-params$metaData

df_data <- df_data_raw %>%
  filter(!exp %in% params$RemoveSample) %>% # filter out unwanted samples
  separate(exp, into = metaData, sep = "_", remove = FALSE) %>%
  mutate(batch = as.factor(str_split_fixed(batch, pattern = "\\s", n = 2)[, 1])) %>% 
  mutate( disp = disp-min(disp), # ensure Disp starts at 0 and not at gel height
    load = load *(-1) # ensure Load is positive
  ) %>% 
  select(!c(calcium, concentration, volume)) %>% 
  mutate(
    alginate = alginate %>%
      forcats::fct_recode("Slow" = "MVG", "Fast" = "VLVG") %>%
      forcats::fct_relevel("Fast", "Slow")
   ) %>% 
  unite(alg_batch, alginate, batch, remove=FALSE)

```

```{r}
# check data quickly
plot_load_time(
  data=df_data,
    x = "time",
    y1= "load",
    id = "alg_batch"
    )
```

# E-modulus analysis

```{r}
# use local file
source(here(path_Rfunctions,"R/bose_analysis/emod_analysis.R"))
```

```{r}
list_emod <- emod_analysis(
    df_data = df_data,
    id = "alg_batch",
    load = "load",
    time = "time",
    disp = "disp",
    groupvar = "alginate",
    gel_height = params$GelProperties$Height,
    gel_r = params$GelProperties$Radius,
    emod_low = params$Emod_low,
    emod_high = params$Emod_high,
    FontSize = params$theme$FontSize
)

df_emod <- list_emod$data
plot_mod <- list_emod$plot
plot_mod
```

```{r}

# create plot with E-Modulus
plot_emod <- plot_summary_points(
  data = df_emod,
  xvar = "alginate",
  yvar= "Emod",
  fillvar= "alginate",
  colors = Color.Gels,
  fontsize = FontSize
) +
  labs(y="Elastic modulus (kPa)")

plot_emod
```

```{r}
plot_emod_stat_list <- add_stat_test_dodge(
   plot_emod, 
    yData = "Emod",
    Group = "alginate",  # groups to compare for stat test, set to NULL when only dodged!
    test = "t.test"
)

plot_emod_stat_list$data_stat

plot_emod_stat <- plot_emod_stat_list$Plot
plot_emod_stat
```

```{r}
# saveRDS(plot_emod_stat, here(Output_dir, "RDS", "plot_emod_stat.rds"))
```

```{r}

create_summary_table(
  data = df_emod,
  columns = "Emod",
  group_columns = "alginate"
)
```

# Stress relaxation analysis

## Fitler signal with butter worth filter

```{r}
source(here(path_Rfunctions, "R/bose_analysis/butterworth_filtering.R"))
```

```{r}

# get only stress relax data
data_stressrelax <- df_data %>%
  group_by(exp) %>%
  mutate(max_time = time[which.max(load)]) %>%  # Get the time at max(load_BF)
  filter(time > max_time) %>%  # Filter for time after max(load_BF) timepoint
  mutate(time = time - max_time) %>%  # Adjust time relative to max(load_BF)
  ungroup()

```

```{r}
data_stressrelax <- butterworth_filtering(
    df_data = data_stressrelax,
    load = "load",    # name of column with load data (string)
    time = "time",    # name of column with time data (string)
    id = "exp" # sample identifier
)
```

```{r}
# check quality of butterworth filter
plot_load_time(
  data = data_stressrelax,
  x = "time",
    y1 = "load",
    id = "exp",
    add_bf = TRUE,
    y2 = "load_BF"
) + 
  scale_y_continuous(limits=c(0,NA), expand = expansion(mult=c(0,0.1)))
```

## thalf analysis

```{r}
# find tHalf
df_thalf <- data_stressrelax %>%
  group_by(exp) %>%
  # mutate(Stress_norm = Load_norm/Area)
  filter(load_norm < 0.5) %>%
  slice_min(time, with_ties = FALSE) %>%
  ungroup()

# plot tHalf
plot_thalf <- plot_summary_points(
    data = df_thalf,
    xvar = "alginate",
    yvar = "time",
    fillvar = "alginate",
    colors = Color.Gels,
    ylimits = c(0, NA),
    fontsize =FontSize,
    pointsize = PointSize,
    linewidth = LineWidth) +
  labs(y=expression("Stress-relaxation " * t[1/2]))

plot_thalf
```

```{r}
# saveRDS(plot_thalf, here(output_dir, "plot_thalf.RDS"))
```

## curve fitting

```{r}
# load custom functions
source(here(path_Rfunctions, "R/bose_analysis", "maxwell_fitting_function.R"))
source(here(path_Rfunctions, "R/bose_analysis", "maxwell_model_definition.R"))
source(here(path_Rfunctions, "R/bose_analysis", "maxwell_main_analysis.R"))
source(here(path_Rfunctions, "R/bose_analysis", "maxwell_plotting_stresscurves.R"))
source(here(path_Rfunctions, "R/bose_analysis", "maxwell_plot_rsquared.R"))

```

```{r}
# perform maxwell fitting to one element model
list_maxwell_results_one <- maxwell_main_analysis(
  df = data_stressrelax,
  t_max = params$tMax,
  model_type = "one",
  id = "alg_batch",
  time = "time",
  fit_var = "load_norm"
)

# perform maxwell fitting to two element model
list_maxwell_results_two <- maxwell_main_analysis(
  df = data_stressrelax,
  t_max = params$tMax,
  model_type = "two",
  id = "alg_batch",
  time = "time",
  fit_var = "load_norm"
)
```

```{r}

# create plots with fitted data
Plot_stresscurves_fitted <- maxwell_plotting_stresscurves(
    result1 = list_maxwell_results_one,
    result2 = list_maxwell_results_two,
    which_models = "both",
    df = data_stressrelax,
    time = "time",
    fit_var = "load_norm",
    color_var = "alginate",
    color_vec = params$Color.Gels,
    t_max = params$tMax,
    id = "alg_batch",
    show_labels = FALSE
  ) +
  scale_y_continuous(limits=c(0,1), expand = expansion(mult=c(0,0)))

Plot_stresscurves_fitted
```

```{r}
create_summary_table(
  data = list_maxwell_results_two$parameters %>% 
    mutate(alginate = str_extract(alg_batch, "Fast|Slow")),
  columns = c("tau1", "tau2", "A1", "A2", "total_relaxation"),
  group_columns = "alginate"
)
```

```{r}

# create df_r_squared
df_r_squared <- full_join(list_maxwell_results_one$r_squared,
                            list_maxwell_results_two$r_squared,
                            by="alg_batch") %>% 
    pivot_longer(cols= starts_with("r_squared"),
                 names_to = "model",
                 values_to = "r_squared") %>% 
    mutate(model = recode(model,
                          "r_squared_one" = "one element",
                          "r_squared_two" = "two element")) %>% 
    mutate(alginate = str_extract(alg_batch, "Fast|Slow")) 

# create plot
plot_r_squared <- plot_summary_points(
  data = df_r_squared,
  xvar = "model",
  yvar = "r_squared",
  fillvar = "alginate",
  Group = "alginate",
  use_dodge = TRUE,
  dodge_width = 0.9, # need to increase dodge_width for coord_cartesian call later
  colors = Color.Gels,
  fontsize = FontSize
) +
  labs(y= expression(R^2))
plot_r_squared

```

```{r}

plot_r_squared_list <- add_stat_test_dodge(
  plot = plot_r_squared,
  yData = "r_squared",
  Group = "model",
  Dodge = "alginate",
  stat_group_by = NULL,
  test = "t.test",
  Facet = NULL,
  paired = FALSE,
  id = NULL,
  FontSize = FontSize,
  yPosition = NULL,
)

plot_r_squared_list$data_stat



# plot_r_squared_stat 
plot_r_squared_list$Plot +
   coord_cartesian(ylim = c(0, 1),
                   expand = FALSE, # no expansion
                   clip = "off") + # use coord_cart instead of scale_y_....
  theme(plot.margin = margin(t = 80, r = 5.5, b = 5.5, l = 5.5, unit = "pt"))
# Plot_rSquared_stat

```

```{r}
# saveRDS(Plot_rSquared_stat, here(output_dir, "Plot_rSquared_stat.rds"))
```

```{r}
create_summary_table(
  data = df_r_squared,
  columns = "r_squared",
  group_columns = c("alginate", "model")
)
```
